name: FE CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  fe-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Optional: quick tree so you can see the repo layout in logs
      - name: Show repo tree
        run: |
          pwd
          ls -la
          echo "---- movie-mood-fe ----"
          ls -la movie-mood-fe || true

      - name: Use Node.js 18.20.3
        uses: actions/setup-node@v4
        with:
          node-version: '18.20.3'
          cache: 'npm'
          cache-dependency-path: movie-mood-fe/package-lock.json

      - name: Install deps (FE)
        working-directory: movie-mood-fe
        run: npm ci

      - name: Sanity check webcrypto
        working-directory: movie-mood-fe
        run: |
          node -e "console.log('has webcrypto?', !!require('node:crypto').webcrypto);"

      - name: Build (FE)
        working-directory: movie-mood-fe
        run: npm run build

      # Optional: save dist as artifact
      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: fe-dist
          path: movie-mood-fe/dist