name: FE CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  fe-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18.20.3
        uses: actions/setup-node@v4
        with:
          node-version: '18.20.3'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install deps
        run: npm ci

      - name: Sanity check webcrypto
        run: |
          node -e "console.log('node:crypto.webcrypto?', !!require('node:crypto').webcrypto)"
          node -e "console.log('globalThis.crypto present before?', !!globalThis.crypto)"
          node -e "globalThis.crypto && console.log('keys:', Object.keys(globalThis.crypto))"

      - name: Build (force no webcrypto)
        run: |
          node -e "delete globalThis.crypto; require('child_process').execSync('npm run build',{stdio:'inherit'})"

      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: fe-dist
          path: dist